// Auto-generated. Do not edit!

// (in-package action_demo.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class LinewalkFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.processing = null;
    }
    else {
      if (initObj.hasOwnProperty('processing')) {
        this.processing = initObj.processing
      }
      else {
        this.processing = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type LinewalkFeedback
    // Serialize message field [processing]
    bufferOffset = _serializer.float32(obj.processing, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type LinewalkFeedback
    let len;
    let data = new LinewalkFeedback(null);
    // Deserialize message field [processing]
    data.processing = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'action_demo/LinewalkFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '937db7b3cae0fa8dd17fd3c334ef4852';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    float32 processing
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new LinewalkFeedback(null);
    if (msg.processing !== undefined) {
      resolved.processing = msg.processing;
    }
    else {
      resolved.processing = 0.0
    }

    return resolved;
    }
};

module.exports = LinewalkFeedback;
