controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - horizental_joint
      - vertical_joint
      - cutting_head_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: initial