(cl:defpackage action_demo-msg
  (:use )
  (:export
   "<LINEWALKACTION>"
   "LINEWALKACTION"
   "<LINEWALKACTIONFEEDBACK>"
   "LINEWALKACTIONFEEDBACK"
   "<LINEWALKACTIONGOAL>"
   "LINEWALKACTIONGOAL"
   "<LINEWALKACTIONRESULT>"
   "LINEWALKACTIONRESULT"
   "<LINEWALKFEEDBACK>"
   "LINEWALKFEEDBACK"
   "<LINEWALKGOAL>"
   "LINEWALKGOAL"
   "<LINEWALKRESULT>"
   "LINEWALKRESULT"
  ))

