; Auto-generated. Do not edit!


(cl:in-package action_demo-msg)


;//! \htmlinclude LinewalkResult.msg.html

(cl:defclass <LinewalkResult> (roslisp-msg-protocol:ros-message)
  ((finished
    :reader finished
    :initarg :finished
    :type cl:integer
    :initform 0))
)

(cl:defclass LinewalkResult (<LinewalkResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LinewalkResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LinewalkResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_demo-msg:<LinewalkResult> is deprecated: use action_demo-msg:LinewalkResult instead.")))

(cl:ensure-generic-function 'finished-val :lambda-list '(m))
(cl:defmethod finished-val ((m <LinewalkResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_demo-msg:finished-val is deprecated.  Use action_demo-msg:finished instead.")
  (finished m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LinewalkResult>) ostream)
  "Serializes a message object of type '<LinewalkResult>"
  (cl:let* ((signed (cl:slot-value msg 'finished)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LinewalkResult>) istream)
  "Deserializes a message object of type '<LinewalkResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'finished) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LinewalkResult>)))
  "Returns string type for a message object of type '<LinewalkResult>"
  "action_demo/LinewalkResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LinewalkResult)))
  "Returns string type for a message object of type 'LinewalkResult"
  "action_demo/LinewalkResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LinewalkResult>)))
  "Returns md5sum for a message object of type '<LinewalkResult>"
  "ba9a45d7caac8cecab90a351b7d250aa")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LinewalkResult)))
  "Returns md5sum for a message object of type 'LinewalkResult"
  "ba9a45d7caac8cecab90a351b7d250aa")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LinewalkResult>)))
  "Returns full string definition for message of type '<LinewalkResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 finished~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LinewalkResult)))
  "Returns full string definition for message of type 'LinewalkResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 finished~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LinewalkResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LinewalkResult>))
  "Converts a ROS message object to a list"
  (cl:list 'LinewalkResult
    (cl:cons ':finished (finished msg))
))
