; Auto-generated. Do not edit!


(cl:in-package action_demo-msg)


;//! \htmlinclude LinewalkFeedback.msg.html

(cl:defclass <LinewalkFeedback> (roslisp-msg-protocol:ros-message)
  ((processing
    :reader processing
    :initarg :processing
    :type cl:float
    :initform 0.0))
)

(cl:defclass LinewalkFeedback (<LinewalkFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LinewalkFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LinewalkFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_demo-msg:<LinewalkFeedback> is deprecated: use action_demo-msg:LinewalkFeedback instead.")))

(cl:ensure-generic-function 'processing-val :lambda-list '(m))
(cl:defmethod processing-val ((m <LinewalkFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_demo-msg:processing-val is deprecated.  Use action_demo-msg:processing instead.")
  (processing m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LinewalkFeedback>) ostream)
  "Serializes a message object of type '<LinewalkFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'processing))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LinewalkFeedback>) istream)
  "Deserializes a message object of type '<LinewalkFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'processing) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LinewalkFeedback>)))
  "Returns string type for a message object of type '<LinewalkFeedback>"
  "action_demo/LinewalkFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LinewalkFeedback)))
  "Returns string type for a message object of type 'LinewalkFeedback"
  "action_demo/LinewalkFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LinewalkFeedback>)))
  "Returns md5sum for a message object of type '<LinewalkFeedback>"
  "937db7b3cae0fa8dd17fd3c334ef4852")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LinewalkFeedback)))
  "Returns md5sum for a message object of type 'LinewalkFeedback"
  "937db7b3cae0fa8dd17fd3c334ef4852")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LinewalkFeedback>)))
  "Returns full string definition for message of type '<LinewalkFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 processing~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LinewalkFeedback)))
  "Returns full string definition for message of type 'LinewalkFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 processing~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LinewalkFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LinewalkFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LinewalkFeedback
    (cl:cons ':processing (processing msg))
))
