// Generated by gencpp from file action_demo/LinewalkFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_DEMO_MESSAGE_LINEWALKFEEDBACK_H
#define ACTION_DEMO_MESSAGE_LINEWALKFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_demo
{
template <class ContainerAllocator>
struct LinewalkFeedback_
{
  typedef LinewalkFeedback_<ContainerAllocator> Type;

  LinewalkFeedback_()
    : processing(0.0)  {
    }
  LinewalkFeedback_(const ContainerAllocator& _alloc)
    : processing(0.0)  {
  (void)_alloc;
    }



   typedef float _processing_type;
  _processing_type processing;





  typedef boost::shared_ptr< ::action_demo::LinewalkFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_demo::LinewalkFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct LinewalkFeedback_

typedef ::action_demo::LinewalkFeedback_<std::allocator<void> > LinewalkFeedback;

typedef boost::shared_ptr< ::action_demo::LinewalkFeedback > LinewalkFeedbackPtr;
typedef boost::shared_ptr< ::action_demo::LinewalkFeedback const> LinewalkFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_demo::LinewalkFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_demo::LinewalkFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_demo::LinewalkFeedback_<ContainerAllocator1> & lhs, const ::action_demo::LinewalkFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.processing == rhs.processing;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_demo::LinewalkFeedback_<ContainerAllocator1> & lhs, const ::action_demo::LinewalkFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::action_demo::LinewalkFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_demo::LinewalkFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_demo::LinewalkFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_demo::LinewalkFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_demo::LinewalkFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_demo::LinewalkFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_demo::LinewalkFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937db7b3cae0fa8dd17fd3c334ef4852";
  }

  static const char* value(const ::action_demo::LinewalkFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937db7b3cae0fa8dULL;
  static const uint64_t static_value2 = 0xd17fd3c334ef4852ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_demo::LinewalkFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_demo/LinewalkFeedback";
  }

  static const char* value(const ::action_demo::LinewalkFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_demo::LinewalkFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float32 processing\n"
"\n"
;
  }

  static const char* value(const ::action_demo::LinewalkFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_demo::LinewalkFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.processing);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinewalkFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_demo::LinewalkFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_demo::LinewalkFeedback_<ContainerAllocator>& v)
  {
    s << indent << "processing: ";
    Printer<float>::stream(s, indent + "  ", v.processing);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_DEMO_MESSAGE_LINEWALKFEEDBACK_H
