// Generated by gencpp from file action_demo/LinewalkResult.msg
// DO NOT EDIT!


#ifndef ACTION_DEMO_MESSAGE_LINEWALKRESULT_H
#define ACTION_DEMO_MESSAGE_LINEWALKRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_demo
{
template <class ContainerAllocator>
struct LinewalkResult_
{
  typedef LinewalkResult_<ContainerAllocator> Type;

  LinewalkResult_()
    : finished(0)  {
    }
  LinewalkResult_(const ContainerAllocator& _alloc)
    : finished(0)  {
  (void)_alloc;
    }



   typedef int32_t _finished_type;
  _finished_type finished;





  typedef boost::shared_ptr< ::action_demo::LinewalkResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_demo::LinewalkResult_<ContainerAllocator> const> ConstPtr;

}; // struct LinewalkResult_

typedef ::action_demo::LinewalkResult_<std::allocator<void> > LinewalkResult;

typedef boost::shared_ptr< ::action_demo::LinewalkResult > LinewalkResultPtr;
typedef boost::shared_ptr< ::action_demo::LinewalkResult const> LinewalkResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_demo::LinewalkResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_demo::LinewalkResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_demo::LinewalkResult_<ContainerAllocator1> & lhs, const ::action_demo::LinewalkResult_<ContainerAllocator2> & rhs)
{
  return lhs.finished == rhs.finished;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_demo::LinewalkResult_<ContainerAllocator1> & lhs, const ::action_demo::LinewalkResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::action_demo::LinewalkResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_demo::LinewalkResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_demo::LinewalkResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_demo::LinewalkResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_demo::LinewalkResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_demo::LinewalkResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_demo::LinewalkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba9a45d7caac8cecab90a351b7d250aa";
  }

  static const char* value(const ::action_demo::LinewalkResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba9a45d7caac8cecULL;
  static const uint64_t static_value2 = 0xab90a351b7d250aaULL;
};

template<class ContainerAllocator>
struct DataType< ::action_demo::LinewalkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_demo/LinewalkResult";
  }

  static const char* value(const ::action_demo::LinewalkResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_demo::LinewalkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"int32 finished\n"
;
  }

  static const char* value(const ::action_demo::LinewalkResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_demo::LinewalkResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finished);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinewalkResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_demo::LinewalkResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_demo::LinewalkResult_<ContainerAllocator>& v)
  {
    s << indent << "finished: ";
    Printer<int32_t>::stream(s, indent + "  ", v.finished);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_DEMO_MESSAGE_LINEWALKRESULT_H
